import {
  Version,
  VersionType,
  World,
  WorldSettings,
} from 'app/src-electron/api/scheme';
import { sleep } from '../utils/testTools';
import { api } from 'app/src-electron/core/api';
import { Failable } from '../../api/failable';

// 処理フロー
// １．フロントがProgressPageに遷移
// ２．フロントからバックのrunServer()を呼び出し
// ３．startServer()でサーバー起動をフロントに通知
// ４．通知を受けてフロントがConsolePageに遷移
// ５．バックよりConsolePageの内容を更新
// （６．フロントよりコマンド入力を受けた場合，バックにコマンドを渡して処理）
export async function runServer(world: World) {
  api.send.UpdateStatus(`${world.settings.version.id} / ${world.name}を起動中`);
  await sleep(2);

  // リモート関連のプログレスバー
  // const array = [...Array(101)].map((_, i) => i);
  // for (let i = 0; i < array.length; i++) {
  //   api.send.UpdateStatus('データをダウンロード中', i);
  //   await sleep(0.1);
  // }

  // LEGACY: Eulaの同意（失敗した場合などのエラー処理も）
  // const options: Electron.MessageBoxOptions = {
  //     type: 'question',
  //     title: 'Server Starter 2',
  //     message: 'Eulaに同意しますか',
  //     buttons: ['はい', 'いいえ'],
  //     cancelId: -1,
  //     defaultId: 0
  // }
  // const res = dialog.showMessageBoxSync(options)
  // console.log(res)

  // Eulaの同意
  // const result = await api.invoke.AgreeEula();
  // console.log('eula:', result);

  // 二，三個の適当なプロセスもどき
  await sleep(2);
  api.send.UpdateStatus('適当なプロセス');
  await sleep(2);
  api.send.UpdateStatus('サーバーを起動するよ');
  await sleep(1);

  // サーバー起動をWindowに知らせる
  api.send.StartServer();

  // サーバーの起動
  // startServer(world)

  // 表示画面にコンソールの中身を順次転送
  for (let i = 0; i < demoConsoles.length; i++) {
    api.send.AddConsole(demoConsoles[i]);
    await sleep(0.25);
  }

  return undefined;
}

export function runCommand(command: string) {
  console.log(command);
  if (command == 'reboot') {
    // TODO: 再起動に関する実装を行う
    api.send.AddConsole('Reboot Server');
  } else {
    api.send.AddConsole(`/${command}`);
  }
}

const demoConsoles = [
  '[00:15:29] [ServerMain/INFO]: Building unoptimized datafixer',
  "[00:15:29] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'",
  '[00:15:31] [ServerMain/INFO]: Loaded 7 recipes',
  '[00:15:31] [ServerMain/INFO]: Loaded 1179 advancements',
  '[00:15:32] [Server thread/INFO]: Starting minecraft server version 1.00.0',
  '[00:15:32] [Server thread/INFO]: Loading properties',
  '[00:15:32] [Server thread/INFO]: Default game type: SURVIVAL',
  '[00:15:32] [Server thread/INFO]: Generating keypair',
  '[00:15:32] [Server thread/INFO]: Starting Minecraft server on *:25565',
  '[00:15:32] [Server thread/INFO]: Using default channel type',
  '[00:15:32] [Server thread/INFO]: Preparing level "worlds/test/world"',
  '[00:15:33] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld',
  '[00:15:35] [Worker-Main-1/INFO]: Preparing spawn area: 0%',
  '[00:15:35] [Worker-Main-1/INFO]: Preparing spawn area: 0%',
  '[00:15:35] [Worker-Main-5/INFO]: Preparing spawn area: 0%',
  '[00:15:35] [Worker-Main-3/INFO]: Preparing spawn area: 0%',
  '[00:15:35] [Worker-Main-6/INFO]: Preparing spawn area: 0%',
  '[00:15:35] [Worker-Main-3/INFO]: Preparing spawn area: 75%',
  '[00:15:35] [Server thread/INFO]: Time elapsed: 2616 ms',
  '[00:15:35] [Server thread/INFO]: Done (3.637s)! For help, type "help"',
  '[00:15:39] [User Authenticator #1/INFO]: UUID of player CivilTT is 7aa8d952-5617-4a8c-8f4f-8761999a1f1a',
  '[00:15:39] [Server thread/INFO]: CivilTT[/127.0.0.1:57745] logged in with entity id 163 at (-47.033365867584706, 27.0, -220.4505154045585)',
  '[00:15:39] [Server thread/INFO]: CivilTT joined the game',
  '[02:05:35] [Server thread/INFO]: CivilTT lost connection: Disconnected',
  '[02:05:35] [Server thread/INFO]: CivilTT left the game',
  '[02:05:41] [Server thread/INFO]: Stopping the server',
  '[02:05:41] [Server thread/INFO]: Stopping server',
  '[02:05:41] [Server thread/INFO]: Saving players',
  '[02:05:41] [Server thread/INFO]: Saving worlds',
  "[02:05:42] [Server thread/INFO]: Saving chunks for level 'ServerLevel[worlds/Saku/world]'/minecraft:overworld",
  "[02:05:43] [Server thread/INFO]: Saving chunks for level 'ServerLevel[worlds/Saku/world]'/minecraft:the_end",
  "[02:05:43] [Server thread/INFO]: Saving chunks for level 'ServerLevel[worlds/Saku/world]'/minecraft:the_nether",
  '[02:05:43] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved',
  '[02:05:43] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved',
  '[02:05:43] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved',
  '[02:05:43] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved',
];

export async function getAllWorlds() {
  function getDemoWorld() {
    const demoWorldSettings: WorldSettings = {
      avater_path: 'https://cdn.quasar.dev/img/parallax2.jpg',
      version: { id: '1.19.2', type: 'vanilla', release: true },
    };
    const demoWorld: World = {
      name: 'testWorld',
      settings: demoWorldSettings,
      datapacks: [],
      plugins: [],
      mods: [],
    };
    return demoWorld;
  }
  return [...Array(10)].map((_) => getDemoWorld());
}

export async function getVersions(
  type: VersionType
): Promise<Failable<Version[]>> {
  return vanillaVersions;
}

const vanillaVersions: Version[] = [
  { type: 'vanilla', release: false, id: '23w16a' },
  { type: 'vanilla', release: false, id: '23w14a' },
  { type: 'vanilla', release: false, id: '23w13a_or_b' },
  { type: 'vanilla', release: false, id: '23w13a' },
  { type: 'vanilla', release: false, id: '23w12a' },
  { type: 'vanilla', release: true, id: '1.19.4' },
  { type: 'vanilla', release: false, id: '1.19.4-rc3' },
  { type: 'vanilla', release: false, id: '1.19.4-rc2' },
  { type: 'vanilla', release: false, id: '1.19.4-rc1' },
  { type: 'vanilla', release: false, id: '1.19.4-pre4' },
  { type: 'vanilla', release: false, id: '1.19.4-pre3' },
  { type: 'vanilla', release: false, id: '1.19.4-pre2' },
  { type: 'vanilla', release: false, id: '1.19.4-pre1' },
  { type: 'vanilla', release: false, id: '23w07a' },
  { type: 'vanilla', release: false, id: '23w06a' },
  { type: 'vanilla', release: false, id: '23w05a' },
  { type: 'vanilla', release: false, id: '23w04a' },
  { type: 'vanilla', release: false, id: '23w03a' },
  { type: 'vanilla', release: true, id: '1.19.3' },
  { type: 'vanilla', release: false, id: '1.19.3-rc3' },
  { type: 'vanilla', release: false, id: '1.19.3-rc2' },
  { type: 'vanilla', release: false, id: '1.19.3-rc1' },
  { type: 'vanilla', release: false, id: '1.19.3-pre3' },
  { type: 'vanilla', release: false, id: '1.19.3-pre2' },
  { type: 'vanilla', release: false, id: '1.19.3-pre1' },
  { type: 'vanilla', release: false, id: '22w46a' },
  { type: 'vanilla', release: false, id: '22w45a' },
  { type: 'vanilla', release: false, id: '22w44a' },
  { type: 'vanilla', release: false, id: '22w43a' },
  { type: 'vanilla', release: false, id: '22w42a' },
  { type: 'vanilla', release: true, id: '1.19.2' },
  { type: 'vanilla', release: false, id: '1.19.2-rc2' },
  { type: 'vanilla', release: false, id: '1.19.2-rc1' },
  { type: 'vanilla', release: true, id: '1.19.1' },
  { type: 'vanilla', release: false, id: '1.19.1-rc3' },
  { type: 'vanilla', release: false, id: '1.19.1-rc2' },
  { type: 'vanilla', release: false, id: '1.19.1-pre6' },
  { type: 'vanilla', release: false, id: '1.19.1-pre5' },
  { type: 'vanilla', release: false, id: '1.19.1-pre4' },
  { type: 'vanilla', release: false, id: '1.19.1-pre3' },
  { type: 'vanilla', release: false, id: '1.19.1-pre2' },
  { type: 'vanilla', release: false, id: '1.19.1-rc1' },
  { type: 'vanilla', release: false, id: '1.19.1-pre1' },
  { type: 'vanilla', release: false, id: '22w24a' },
  { type: 'vanilla', release: true, id: '1.19' },
  { type: 'vanilla', release: false, id: '1.19-rc2' },
  { type: 'vanilla', release: false, id: '1.19-rc1' },
  { type: 'vanilla', release: false, id: '1.19-pre5' },
  { type: 'vanilla', release: false, id: '1.19-pre4' },
  { type: 'vanilla', release: false, id: '1.19-pre3' },
  { type: 'vanilla', release: false, id: '1.19-pre2' },
  { type: 'vanilla', release: false, id: '1.19-pre1' },
  { type: 'vanilla', release: false, id: '22w19a' },
  { type: 'vanilla', release: false, id: '22w18a' },
  { type: 'vanilla', release: false, id: '22w17a' },
  { type: 'vanilla', release: false, id: '22w16b' },
  { type: 'vanilla', release: false, id: '22w16a' },
  { type: 'vanilla', release: false, id: '22w15a' },
  { type: 'vanilla', release: false, id: '22w14a' },
  { type: 'vanilla', release: false, id: '22w13oneblockatatime' },
  { type: 'vanilla', release: false, id: '22w13a' },
  { type: 'vanilla', release: false, id: '22w12a' },
  { type: 'vanilla', release: false, id: '22w11a' },
  { type: 'vanilla', release: true, id: '1.18.2' },
  { type: 'vanilla', release: false, id: '1.18.2-rc1' },
  { type: 'vanilla', release: false, id: '1.18.2-pre3' },
  { type: 'vanilla', release: false, id: '1.18.2-pre2' },
  { type: 'vanilla', release: false, id: '1.18.2-pre1' },
  { type: 'vanilla', release: false, id: '22w07a' },
  { type: 'vanilla', release: false, id: '22w06a' },
  { type: 'vanilla', release: false, id: '22w05a' },
  { type: 'vanilla', release: false, id: '22w03a' },
  { type: 'vanilla', release: true, id: '1.18.1' },
  { type: 'vanilla', release: false, id: '1.18.1-rc3' },
  { type: 'vanilla', release: false, id: '1.18.1-rc2' },
  { type: 'vanilla', release: false, id: '1.18.1-rc1' },
  { type: 'vanilla', release: false, id: '1.18.1-pre1' },
  { type: 'vanilla', release: true, id: '1.18' },
  { type: 'vanilla', release: false, id: '1.18-rc4' },
  { type: 'vanilla', release: false, id: '1.18-rc3' },
  { type: 'vanilla', release: false, id: '1.18-rc2' },
  { type: 'vanilla', release: false, id: '1.18-rc1' },
  { type: 'vanilla', release: false, id: '1.18-pre8' },
  { type: 'vanilla', release: false, id: '1.18-pre7' },
  { type: 'vanilla', release: false, id: '1.18-pre6' },
  { type: 'vanilla', release: false, id: '1.18-pre5' },
  { type: 'vanilla', release: false, id: '1.18-pre4' },
  { type: 'vanilla', release: false, id: '1.18-pre3' },
  { type: 'vanilla', release: false, id: '1.18-pre2' },
  { type: 'vanilla', release: false, id: '1.18-pre1' },
  { type: 'vanilla', release: false, id: '21w44a' },
  { type: 'vanilla', release: false, id: '21w43a' },
  { type: 'vanilla', release: false, id: '21w42a' },
  { type: 'vanilla', release: false, id: '21w41a' },
  { type: 'vanilla', release: false, id: '21w40a' },
  { type: 'vanilla', release: false, id: '21w39a' },
  { type: 'vanilla', release: false, id: '21w38a' },
  { type: 'vanilla', release: false, id: '21w37a' },
  { type: 'vanilla', release: true, id: '1.17.1' },
  { type: 'vanilla', release: false, id: '1.17.1-rc2' },
  { type: 'vanilla', release: false, id: '1.17.1-rc1' },
  { type: 'vanilla', release: false, id: '1.17.1-pre3' },
  { type: 'vanilla', release: false, id: '1.17.1-pre2' },
  { type: 'vanilla', release: false, id: '1.17.1-pre1' },
  { type: 'vanilla', release: true, id: '1.17' },
  { type: 'vanilla', release: false, id: '1.17-rc2' },
  { type: 'vanilla', release: false, id: '1.17-rc1' },
  { type: 'vanilla', release: false, id: '1.17-pre5' },
  { type: 'vanilla', release: false, id: '1.17-pre4' },
  { type: 'vanilla', release: false, id: '1.17-pre3' },
  { type: 'vanilla', release: false, id: '1.17-pre2' },
  { type: 'vanilla', release: false, id: '1.17-pre1' },
  { type: 'vanilla', release: false, id: '21w20a' },
  { type: 'vanilla', release: false, id: '21w19a' },
  { type: 'vanilla', release: false, id: '21w18a' },
  { type: 'vanilla', release: false, id: '21w17a' },
  { type: 'vanilla', release: false, id: '21w16a' },
  { type: 'vanilla', release: false, id: '21w15a' },
  { type: 'vanilla', release: false, id: '21w14a' },
  { type: 'vanilla', release: false, id: '21w13a' },
  { type: 'vanilla', release: false, id: '21w11a' },
  { type: 'vanilla', release: false, id: '21w10a' },
  { type: 'vanilla', release: false, id: '21w08b' },
  { type: 'vanilla', release: false, id: '21w08a' },
  { type: 'vanilla', release: false, id: '21w07a' },
  { type: 'vanilla', release: false, id: '21w06a' },
  { type: 'vanilla', release: false, id: '21w05b' },
  { type: 'vanilla', release: false, id: '21w05a' },
  { type: 'vanilla', release: false, id: '21w03a' },
  { type: 'vanilla', release: true, id: '1.16.5' },
  { type: 'vanilla', release: false, id: '1.16.5-rc1' },
  { type: 'vanilla', release: false, id: '20w51a' },
  { type: 'vanilla', release: false, id: '20w49a' },
  { type: 'vanilla', release: false, id: '20w48a' },
  { type: 'vanilla', release: false, id: '20w46a' },
  { type: 'vanilla', release: false, id: '20w45a' },
  { type: 'vanilla', release: true, id: '1.16.4' },
  { type: 'vanilla', release: false, id: '1.16.4-rc1' },
  { type: 'vanilla', release: false, id: '1.16.4-pre2' },
  { type: 'vanilla', release: false, id: '1.16.4-pre1' },
  { type: 'vanilla', release: true, id: '1.16.3' },
  { type: 'vanilla', release: false, id: '1.16.3-rc1' },
  { type: 'vanilla', release: true, id: '1.16.2' },
  { type: 'vanilla', release: false, id: '1.16.2-rc2' },
  { type: 'vanilla', release: false, id: '1.16.2-rc1' },
  { type: 'vanilla', release: false, id: '1.16.2-pre3' },
  { type: 'vanilla', release: false, id: '1.16.2-pre2' },
  { type: 'vanilla', release: false, id: '1.16.2-pre1' },
  { type: 'vanilla', release: false, id: '20w30a' },
  { type: 'vanilla', release: false, id: '20w29a' },
  { type: 'vanilla', release: false, id: '20w28a' },
  { type: 'vanilla', release: false, id: '20w27a' },
  { type: 'vanilla', release: true, id: '1.16.1' },
  { type: 'vanilla', release: true, id: '1.16' },
  { type: 'vanilla', release: false, id: '1.16-rc1' },
  { type: 'vanilla', release: false, id: '1.16-pre8' },
  { type: 'vanilla', release: false, id: '1.16-pre7' },
  { type: 'vanilla', release: false, id: '1.16-pre6' },
  { type: 'vanilla', release: false, id: '1.16-pre5' },
  { type: 'vanilla', release: false, id: '1.16-pre4' },
  { type: 'vanilla', release: false, id: '1.16-pre3' },
  { type: 'vanilla', release: false, id: '1.16-pre2' },
  { type: 'vanilla', release: false, id: '1.16-pre1' },
  { type: 'vanilla', release: false, id: '20w22a' },
  { type: 'vanilla', release: false, id: '20w21a' },
  { type: 'vanilla', release: false, id: '20w20b' },
  { type: 'vanilla', release: false, id: '20w20a' },
  { type: 'vanilla', release: false, id: '20w19a' },
  { type: 'vanilla', release: false, id: '20w18a' },
  { type: 'vanilla', release: false, id: '20w17a' },
  { type: 'vanilla', release: false, id: '20w16a' },
  { type: 'vanilla', release: false, id: '20w15a' },
  { type: 'vanilla', release: false, id: '20w14a' },
  { type: 'vanilla', release: false, id: '20w14infinite' },
  { type: 'vanilla', release: false, id: '20w13b' },
  { type: 'vanilla', release: false, id: '20w13a' },
  { type: 'vanilla', release: false, id: '20w12a' },
  { type: 'vanilla', release: false, id: '20w11a' },
  { type: 'vanilla', release: false, id: '20w10a' },
  { type: 'vanilla', release: false, id: '20w09a' },
  { type: 'vanilla', release: false, id: '20w08a' },
  { type: 'vanilla', release: false, id: '20w07a' },
  { type: 'vanilla', release: false, id: '20w06a' },
  { type: 'vanilla', release: true, id: '1.15.2' },
  { type: 'vanilla', release: false, id: '1.15.2-pre2' },
  { type: 'vanilla', release: false, id: '1.15.2-pre1' },
  { type: 'vanilla', release: true, id: '1.15.1' },
  { type: 'vanilla', release: false, id: '1.15.1-pre1' },
  { type: 'vanilla', release: true, id: '1.15' },
  { type: 'vanilla', release: false, id: '1.15-pre7' },
  { type: 'vanilla', release: false, id: '1.15-pre6' },
  { type: 'vanilla', release: false, id: '1.15-pre5' },
  { type: 'vanilla', release: false, id: '1.15-pre4' },
  { type: 'vanilla', release: false, id: '1.15-pre3' },
  { type: 'vanilla', release: false, id: '1.15-pre2' },
  { type: 'vanilla', release: false, id: '1.15-pre1' },
  { type: 'vanilla', release: false, id: '19w46b' },
  { type: 'vanilla', release: false, id: '19w46a' },
  { type: 'vanilla', release: false, id: '19w45b' },
  { type: 'vanilla', release: false, id: '19w45a' },
  { type: 'vanilla', release: false, id: '19w44a' },
  { type: 'vanilla', release: false, id: '19w42a' },
  { type: 'vanilla', release: false, id: '19w41a' },
  { type: 'vanilla', release: false, id: '19w40a' },
  { type: 'vanilla', release: false, id: '19w39a' },
  { type: 'vanilla', release: false, id: '19w38b' },
  { type: 'vanilla', release: false, id: '19w38a' },
  { type: 'vanilla', release: false, id: '19w37a' },
  { type: 'vanilla', release: false, id: '19w36a' },
  { type: 'vanilla', release: false, id: '19w35a' },
  { type: 'vanilla', release: false, id: '19w34a' },
  { type: 'vanilla', release: true, id: '1.14.4' },
  { type: 'vanilla', release: false, id: '1.14.4-pre7' },
  { type: 'vanilla', release: false, id: '1.14.4-pre6' },
  { type: 'vanilla', release: false, id: '1.14.4-pre5' },
  { type: 'vanilla', release: false, id: '1.14.4-pre4' },
  { type: 'vanilla', release: false, id: '1.14.4-pre3' },
  { type: 'vanilla', release: false, id: '1.14.4-pre2' },
  { type: 'vanilla', release: false, id: '1.14.4-pre1' },
  { type: 'vanilla', release: true, id: '1.14.3' },
  { type: 'vanilla', release: false, id: '1.14.3-pre4' },
  { type: 'vanilla', release: false, id: '1.14.3-pre3' },
  { type: 'vanilla', release: false, id: '1.14.3-pre2' },
  { type: 'vanilla', release: false, id: '1.14.3-pre1' },
  { type: 'vanilla', release: true, id: '1.14.2' },
  { type: 'vanilla', release: false, id: '1.14.2 Pre-Release 4' },
  { type: 'vanilla', release: false, id: '1.14.2 Pre-Release 3' },
  { type: 'vanilla', release: false, id: '1.14.2 Pre-Release 2' },
  { type: 'vanilla', release: false, id: '1.14.2 Pre-Release 1' },
  { type: 'vanilla', release: true, id: '1.14.1' },
  { type: 'vanilla', release: false, id: '1.14.1 Pre-Release 2' },
  { type: 'vanilla', release: false, id: '1.14.1 Pre-Release 1' },
  { type: 'vanilla', release: true, id: '1.14' },
  { type: 'vanilla', release: false, id: '1.14 Pre-Release 5' },
  { type: 'vanilla', release: false, id: '1.14 Pre-Release 4' },
  { type: 'vanilla', release: false, id: '1.14 Pre-Release 3' },
  { type: 'vanilla', release: false, id: '1.14 Pre-Release 2' },
  { type: 'vanilla', release: false, id: '1.14 Pre-Release 1' },
  { type: 'vanilla', release: false, id: '19w14b' },
  { type: 'vanilla', release: false, id: '19w14a' },
  { type: 'vanilla', release: false, id: '3D Shareware v1.34' },
  { type: 'vanilla', release: false, id: '19w13b' },
  { type: 'vanilla', release: false, id: '19w13a' },
  { type: 'vanilla', release: false, id: '19w12b' },
  { type: 'vanilla', release: false, id: '19w12a' },
  { type: 'vanilla', release: false, id: '19w11b' },
  { type: 'vanilla', release: false, id: '19w11a' },
  { type: 'vanilla', release: false, id: '19w09a' },
  { type: 'vanilla', release: false, id: '19w08b' },
  { type: 'vanilla', release: false, id: '19w08a' },
  { type: 'vanilla', release: false, id: '19w07a' },
  { type: 'vanilla', release: false, id: '19w06a' },
  { type: 'vanilla', release: false, id: '19w05a' },
  { type: 'vanilla', release: false, id: '19w04b' },
  { type: 'vanilla', release: false, id: '19w04a' },
  { type: 'vanilla', release: false, id: '19w03c' },
  { type: 'vanilla', release: false, id: '19w03b' },
  { type: 'vanilla', release: false, id: '19w03a' },
  { type: 'vanilla', release: false, id: '19w02a' },
  { type: 'vanilla', release: false, id: '18w50a' },
  { type: 'vanilla', release: false, id: '18w49a' },
  { type: 'vanilla', release: false, id: '18w48b' },
  { type: 'vanilla', release: false, id: '18w48a' },
  { type: 'vanilla', release: false, id: '18w47b' },
  { type: 'vanilla', release: false, id: '18w47a' },
  { type: 'vanilla', release: false, id: '18w46a' },
  { type: 'vanilla', release: false, id: '18w45a' },
  { type: 'vanilla', release: false, id: '18w44a' },
  { type: 'vanilla', release: false, id: '18w43c' },
  { type: 'vanilla', release: false, id: '18w43b' },
  { type: 'vanilla', release: false, id: '18w43a' },
  { type: 'vanilla', release: true, id: '1.13.2' },
  { type: 'vanilla', release: false, id: '1.13.2-pre2' },
  { type: 'vanilla', release: false, id: '1.13.2-pre1' },
  { type: 'vanilla', release: true, id: '1.13.1' },
  { type: 'vanilla', release: false, id: '1.13.1-pre2' },
  { type: 'vanilla', release: false, id: '1.13.1-pre1' },
  { type: 'vanilla', release: false, id: '18w33a' },
  { type: 'vanilla', release: false, id: '18w32a' },
  { type: 'vanilla', release: false, id: '18w31a' },
  { type: 'vanilla', release: false, id: '18w30b' },
  { type: 'vanilla', release: false, id: '18w30a' },
  { type: 'vanilla', release: true, id: '1.13' },
  { type: 'vanilla', release: false, id: '1.13-pre10' },
  { type: 'vanilla', release: false, id: '1.13-pre9' },
  { type: 'vanilla', release: false, id: '1.13-pre8' },
  { type: 'vanilla', release: false, id: '1.13-pre7' },
  { type: 'vanilla', release: false, id: '1.13-pre6' },
  { type: 'vanilla', release: false, id: '1.13-pre5' },
  { type: 'vanilla', release: false, id: '1.13-pre4' },
  { type: 'vanilla', release: false, id: '1.13-pre3' },
  { type: 'vanilla', release: false, id: '1.13-pre2' },
  { type: 'vanilla', release: false, id: '1.13-pre1' },
  { type: 'vanilla', release: false, id: '18w22c' },
  { type: 'vanilla', release: false, id: '18w22b' },
  { type: 'vanilla', release: false, id: '18w22a' },
  { type: 'vanilla', release: false, id: '18w21b' },
  { type: 'vanilla', release: false, id: '18w21a' },
  { type: 'vanilla', release: false, id: '18w20c' },
  { type: 'vanilla', release: false, id: '18w20b' },
  { type: 'vanilla', release: false, id: '18w20a' },
  { type: 'vanilla', release: false, id: '18w19b' },
  { type: 'vanilla', release: false, id: '18w19a' },
  { type: 'vanilla', release: false, id: '18w16a' },
  { type: 'vanilla', release: false, id: '18w15a' },
  { type: 'vanilla', release: false, id: '18w14b' },
  { type: 'vanilla', release: false, id: '18w14a' },
  { type: 'vanilla', release: false, id: '18w11a' },
  { type: 'vanilla', release: false, id: '18w10d' },
  { type: 'vanilla', release: false, id: '18w10c' },
  { type: 'vanilla', release: false, id: '18w10b' },
  { type: 'vanilla', release: false, id: '18w10a' },
  { type: 'vanilla', release: false, id: '18w09a' },
  { type: 'vanilla', release: false, id: '18w08b' },
  { type: 'vanilla', release: false, id: '18w08a' },
  { type: 'vanilla', release: false, id: '18w07c' },
  { type: 'vanilla', release: false, id: '18w07b' },
  { type: 'vanilla', release: false, id: '18w07a' },
  { type: 'vanilla', release: false, id: '18w06a' },
  { type: 'vanilla', release: false, id: '18w05a' },
  { type: 'vanilla', release: false, id: '18w03b' },
  { type: 'vanilla', release: false, id: '18w03a' },
  { type: 'vanilla', release: false, id: '18w02a' },
  { type: 'vanilla', release: false, id: '18w01a' },
  { type: 'vanilla', release: false, id: '17w50a' },
  { type: 'vanilla', release: false, id: '17w49b' },
  { type: 'vanilla', release: false, id: '17w49a' },
  { type: 'vanilla', release: false, id: '17w48a' },
  { type: 'vanilla', release: false, id: '17w47b' },
  { type: 'vanilla', release: false, id: '17w47a' },
  { type: 'vanilla', release: false, id: '17w46a' },
  { type: 'vanilla', release: false, id: '17w45b' },
  { type: 'vanilla', release: false, id: '17w45a' },
  { type: 'vanilla', release: false, id: '17w43b' },
  { type: 'vanilla', release: false, id: '17w43a' },
  { type: 'vanilla', release: true, id: '1.12.2' },
  { type: 'vanilla', release: false, id: '1.12.2-pre2' },
  { type: 'vanilla', release: false, id: '1.12.2-pre1' },
  { type: 'vanilla', release: true, id: '1.12.1' },
  { type: 'vanilla', release: false, id: '1.12.1-pre1' },
  { type: 'vanilla', release: false, id: '17w31a' },
  { type: 'vanilla', release: true, id: '1.12' },
  { type: 'vanilla', release: false, id: '1.12-pre7' },
  { type: 'vanilla', release: false, id: '1.12-pre6' },
  { type: 'vanilla', release: false, id: '1.12-pre5' },
  { type: 'vanilla', release: false, id: '1.12-pre4' },
  { type: 'vanilla', release: false, id: '1.12-pre3' },
  { type: 'vanilla', release: false, id: '1.12-pre2' },
  { type: 'vanilla', release: false, id: '1.12-pre1' },
  { type: 'vanilla', release: false, id: '17w18b' },
  { type: 'vanilla', release: false, id: '17w18a' },
  { type: 'vanilla', release: false, id: '17w17b' },
  { type: 'vanilla', release: false, id: '17w17a' },
  { type: 'vanilla', release: false, id: '17w16b' },
  { type: 'vanilla', release: false, id: '17w16a' },
  { type: 'vanilla', release: false, id: '17w15a' },
  { type: 'vanilla', release: false, id: '17w14a' },
  { type: 'vanilla', release: false, id: '17w13b' },
  { type: 'vanilla', release: false, id: '17w13a' },
  { type: 'vanilla', release: false, id: '17w06a' },
  { type: 'vanilla', release: true, id: '1.11.2' },
  { type: 'vanilla', release: true, id: '1.11.1' },
  { type: 'vanilla', release: false, id: '16w50a' },
  { type: 'vanilla', release: true, id: '1.11' },
  { type: 'vanilla', release: false, id: '1.11-pre1' },
  { type: 'vanilla', release: false, id: '16w44a' },
  { type: 'vanilla', release: false, id: '16w43a' },
  { type: 'vanilla', release: false, id: '16w42a' },
  { type: 'vanilla', release: false, id: '16w41a' },
  { type: 'vanilla', release: false, id: '16w40a' },
  { type: 'vanilla', release: false, id: '16w39c' },
  { type: 'vanilla', release: false, id: '16w39b' },
  { type: 'vanilla', release: false, id: '16w39a' },
  { type: 'vanilla', release: false, id: '16w38a' },
  { type: 'vanilla', release: false, id: '16w36a' },
  { type: 'vanilla', release: false, id: '16w35a' },
  { type: 'vanilla', release: false, id: '16w33a' },
  { type: 'vanilla', release: false, id: '16w32b' },
  { type: 'vanilla', release: false, id: '16w32a' },
  { type: 'vanilla', release: true, id: '1.10.2' },
  { type: 'vanilla', release: true, id: '1.10.1' },
  { type: 'vanilla', release: true, id: '1.10' },
  { type: 'vanilla', release: false, id: '1.10-pre2' },
  { type: 'vanilla', release: false, id: '1.10-pre1' },
  { type: 'vanilla', release: false, id: '16w21b' },
  { type: 'vanilla', release: false, id: '16w21a' },
  { type: 'vanilla', release: false, id: '16w20a' },
  { type: 'vanilla', release: true, id: '1.9.4' },
  { type: 'vanilla', release: true, id: '1.9.3' },
  { type: 'vanilla', release: false, id: '1.9.3-pre3' },
  { type: 'vanilla', release: false, id: '1.9.3-pre2' },
  { type: 'vanilla', release: false, id: '1.9.3-pre1' },
  { type: 'vanilla', release: false, id: '16w15b' },
  { type: 'vanilla', release: false, id: '16w15a' },
  { type: 'vanilla', release: false, id: '16w14a' },
  { type: 'vanilla', release: false, id: '1.RV-Pre1' },
  { type: 'vanilla', release: true, id: '1.9.2' },
  { type: 'vanilla', release: true, id: '1.9.1' },
  { type: 'vanilla', release: false, id: '1.9.1-pre3' },
  { type: 'vanilla', release: false, id: '1.9.1-pre2' },
  { type: 'vanilla', release: false, id: '1.9.1-pre1' },
  { type: 'vanilla', release: true, id: '1.9' },
  { type: 'vanilla', release: false, id: '1.9-pre4' },
  { type: 'vanilla', release: false, id: '1.9-pre3' },
  { type: 'vanilla', release: false, id: '1.9-pre2' },
  { type: 'vanilla', release: false, id: '1.9-pre1' },
  { type: 'vanilla', release: false, id: '16w07b' },
  { type: 'vanilla', release: false, id: '16w07a' },
  { type: 'vanilla', release: false, id: '16w06a' },
  { type: 'vanilla', release: false, id: '16w05b' },
  { type: 'vanilla', release: false, id: '16w05a' },
  { type: 'vanilla', release: false, id: '16w04a' },
  { type: 'vanilla', release: false, id: '16w03a' },
  { type: 'vanilla', release: false, id: '16w02a' },
  { type: 'vanilla', release: false, id: '15w51b' },
  { type: 'vanilla', release: false, id: '15w51a' },
  { type: 'vanilla', release: false, id: '15w50a' },
  { type: 'vanilla', release: false, id: '15w49b' },
  { type: 'vanilla', release: true, id: '1.8.9' },
  { type: 'vanilla', release: false, id: '15w49a' },
  { type: 'vanilla', release: false, id: '15w47c' },
  { type: 'vanilla', release: false, id: '15w47b' },
  { type: 'vanilla', release: false, id: '15w47a' },
  { type: 'vanilla', release: false, id: '15w46a' },
  { type: 'vanilla', release: false, id: '15w45a' },
  { type: 'vanilla', release: false, id: '15w44b' },
  { type: 'vanilla', release: false, id: '15w44a' },
  { type: 'vanilla', release: false, id: '15w43c' },
  { type: 'vanilla', release: false, id: '15w43b' },
  { type: 'vanilla', release: false, id: '15w43a' },
  { type: 'vanilla', release: false, id: '15w42a' },
  { type: 'vanilla', release: false, id: '15w41b' },
  { type: 'vanilla', release: false, id: '15w41a' },
  { type: 'vanilla', release: false, id: '15w40b' },
  { type: 'vanilla', release: false, id: '15w40a' },
  { type: 'vanilla', release: false, id: '15w39c' },
  { type: 'vanilla', release: false, id: '15w39b' },
  { type: 'vanilla', release: false, id: '15w39a' },
  { type: 'vanilla', release: false, id: '15w38b' },
  { type: 'vanilla', release: false, id: '15w38a' },
  { type: 'vanilla', release: false, id: '15w37a' },
  { type: 'vanilla', release: false, id: '15w36d' },
  { type: 'vanilla', release: false, id: '15w36c' },
  { type: 'vanilla', release: false, id: '15w36b' },
  { type: 'vanilla', release: false, id: '15w36a' },
  { type: 'vanilla', release: false, id: '15w35e' },
  { type: 'vanilla', release: false, id: '15w35d' },
  { type: 'vanilla', release: false, id: '15w35c' },
  { type: 'vanilla', release: false, id: '15w35b' },
  { type: 'vanilla', release: false, id: '15w35a' },
  { type: 'vanilla', release: false, id: '15w34d' },
  { type: 'vanilla', release: false, id: '15w34c' },
  { type: 'vanilla', release: false, id: '15w34b' },
  { type: 'vanilla', release: false, id: '15w34a' },
  { type: 'vanilla', release: false, id: '15w33c' },
  { type: 'vanilla', release: false, id: '15w33b' },
  { type: 'vanilla', release: false, id: '15w33a' },
  { type: 'vanilla', release: false, id: '15w32c' },
  { type: 'vanilla', release: false, id: '15w32b' },
  { type: 'vanilla', release: false, id: '15w32a' },
  { type: 'vanilla', release: false, id: '15w31c' },
  { type: 'vanilla', release: false, id: '15w31b' },
  { type: 'vanilla', release: false, id: '15w31a' },
  { type: 'vanilla', release: true, id: '1.8.8' },
  { type: 'vanilla', release: true, id: '1.8.7' },
  { type: 'vanilla', release: true, id: '1.8.6' },
  { type: 'vanilla', release: true, id: '1.8.5' },
  { type: 'vanilla', release: true, id: '1.8.4' },
  { type: 'vanilla', release: false, id: '15w14a' },
  { type: 'vanilla', release: true, id: '1.8.3' },
  { type: 'vanilla', release: true, id: '1.8.2' },
  { type: 'vanilla', release: false, id: '1.8.2-pre7' },
  { type: 'vanilla', release: false, id: '1.8.2-pre6' },
  { type: 'vanilla', release: false, id: '1.8.2-pre5' },
  { type: 'vanilla', release: false, id: '1.8.2-pre4' },
  { type: 'vanilla', release: false, id: '1.8.2-pre3' },
  { type: 'vanilla', release: false, id: '1.8.2-pre2' },
  { type: 'vanilla', release: false, id: '1.8.2-pre1' },
  { type: 'vanilla', release: true, id: '1.8.1' },
  { type: 'vanilla', release: false, id: '1.8.1-pre5' },
  { type: 'vanilla', release: false, id: '1.8.1-pre4' },
  { type: 'vanilla', release: false, id: '1.8.1-pre3' },
  { type: 'vanilla', release: false, id: '1.8.1-pre2' },
  { type: 'vanilla', release: false, id: '1.8.1-pre1' },
  { type: 'vanilla', release: true, id: '1.8' },
  { type: 'vanilla', release: false, id: '1.8-pre3' },
  { type: 'vanilla', release: false, id: '1.8-pre2' },
  { type: 'vanilla', release: false, id: '1.8-pre1' },
  { type: 'vanilla', release: false, id: '14w34d' },
  { type: 'vanilla', release: false, id: '14w34c' },
  { type: 'vanilla', release: false, id: '14w34b' },
  { type: 'vanilla', release: false, id: '14w34a' },
  { type: 'vanilla', release: false, id: '14w33c' },
  { type: 'vanilla', release: false, id: '14w33b' },
  { type: 'vanilla', release: false, id: '14w33a' },
  { type: 'vanilla', release: false, id: '14w32d' },
  { type: 'vanilla', release: false, id: '14w32c' },
  { type: 'vanilla', release: false, id: '14w32b' },
  { type: 'vanilla', release: false, id: '14w32a' },
  { type: 'vanilla', release: false, id: '14w31a' },
  { type: 'vanilla', release: false, id: '14w30c' },
  { type: 'vanilla', release: false, id: '14w30b' },
  { type: 'vanilla', release: false, id: '14w30a' },
  { type: 'vanilla', release: false, id: '14w29b' },
  { type: 'vanilla', release: false, id: '14w29a' },
  { type: 'vanilla', release: false, id: '14w28b' },
  { type: 'vanilla', release: false, id: '14w28a' },
  { type: 'vanilla', release: false, id: '14w27b' },
  { type: 'vanilla', release: false, id: '14w27a' },
  { type: 'vanilla', release: false, id: '14w26c' },
  { type: 'vanilla', release: false, id: '14w26b' },
  { type: 'vanilla', release: false, id: '14w26a' },
  { type: 'vanilla', release: false, id: '14w25b' },
  { type: 'vanilla', release: false, id: '14w25a' },
  { type: 'vanilla', release: false, id: '14w21b' },
  { type: 'vanilla', release: false, id: '14w21a' },
  { type: 'vanilla', release: false, id: '14w20b' },
  { type: 'vanilla', release: false, id: '14w20a' },
  { type: 'vanilla', release: true, id: '1.7.10' },
  { type: 'vanilla', release: false, id: '1.7.10-pre4' },
  { type: 'vanilla', release: false, id: '1.7.10-pre3' },
  { type: 'vanilla', release: false, id: '1.7.10-pre2' },
  { type: 'vanilla', release: false, id: '1.7.10-pre1' },
  { type: 'vanilla', release: false, id: '14w19a' },
  { type: 'vanilla', release: false, id: '14w18b' },
  { type: 'vanilla', release: false, id: '14w18a' },
  { type: 'vanilla', release: false, id: '14w17a' },
  { type: 'vanilla', release: false, id: '14w11b' },
  { type: 'vanilla', release: true, id: '1.7.9' },
  { type: 'vanilla', release: true, id: '1.7.8' },
  { type: 'vanilla', release: true, id: '1.7.7' },
  { type: 'vanilla', release: true, id: '1.7.6' },
  { type: 'vanilla', release: false, id: '14w11a' },
  { type: 'vanilla', release: false, id: '1.7.6-pre2' },
  { type: 'vanilla', release: false, id: '1.7.6-pre1' },
  { type: 'vanilla', release: false, id: '14w10c' },
  { type: 'vanilla', release: false, id: '14w10b' },
  { type: 'vanilla', release: false, id: '14w10a' },
  { type: 'vanilla', release: false, id: '14w08a' },
  { type: 'vanilla', release: true, id: '1.7.5' },
  { type: 'vanilla', release: false, id: '14w07a' },
  { type: 'vanilla', release: false, id: '14w06b' },
  { type: 'vanilla', release: false, id: '14w06a' },
  { type: 'vanilla', release: false, id: '14w05b' },
  { type: 'vanilla', release: false, id: '14w05a' },
  { type: 'vanilla', release: false, id: '14w04b' },
  { type: 'vanilla', release: false, id: '14w04a' },
  { type: 'vanilla', release: false, id: '14w03b' },
  { type: 'vanilla', release: false, id: '14w03a' },
  { type: 'vanilla', release: false, id: '14w02c' },
  { type: 'vanilla', release: false, id: '14w02b' },
  { type: 'vanilla', release: false, id: '14w02a' },
  { type: 'vanilla', release: true, id: '1.7.4' },
  { type: 'vanilla', release: true, id: '1.7.3' },
  { type: 'vanilla', release: false, id: '13w49a' },
  { type: 'vanilla', release: false, id: '13w48b' },
  { type: 'vanilla', release: false, id: '13w48a' },
  { type: 'vanilla', release: false, id: '13w47e' },
  { type: 'vanilla', release: false, id: '13w47d' },
  { type: 'vanilla', release: false, id: '13w47c' },
  { type: 'vanilla', release: false, id: '13w47b' },
  { type: 'vanilla', release: false, id: '13w47a' },
  { type: 'vanilla', release: true, id: '1.7.2' },
  { type: 'vanilla', release: false, id: '1.7.1' },
  { type: 'vanilla', release: false, id: '1.7' },
  { type: 'vanilla', release: false, id: '13w43a' },
  { type: 'vanilla', release: false, id: '13w42b' },
  { type: 'vanilla', release: false, id: '13w42a' },
  { type: 'vanilla', release: false, id: '13w41b' },
  { type: 'vanilla', release: false, id: '13w41a' },
  { type: 'vanilla', release: false, id: '13w39b' },
  { type: 'vanilla', release: false, id: '13w39a' },
  { type: 'vanilla', release: false, id: '13w38c' },
  { type: 'vanilla', release: false, id: '13w38b' },
  { type: 'vanilla', release: false, id: '13w38a' },
  { type: 'vanilla', release: true, id: '1.6.4' },
  { type: 'vanilla', release: false, id: '13w37b' },
  { type: 'vanilla', release: false, id: '1.6.3' },
  { type: 'vanilla', release: false, id: '13w37a' },
  { type: 'vanilla', release: false, id: '13w36b' },
  { type: 'vanilla', release: false, id: '13w36a' },
  { type: 'vanilla', release: true, id: '1.6.2' },
  { type: 'vanilla', release: true, id: '1.6.1' },
  { type: 'vanilla', release: false, id: '1.6' },
  { type: 'vanilla', release: false, id: '13w26a' },
  { type: 'vanilla', release: false, id: '13w25c' },
  { type: 'vanilla', release: false, id: '13w25b' },
  { type: 'vanilla', release: false, id: '13w25a' },
  { type: 'vanilla', release: false, id: '13w24b' },
  { type: 'vanilla', release: false, id: '13w24a' },
  { type: 'vanilla', release: false, id: '13w23b' },
  { type: 'vanilla', release: false, id: '13w23a' },
  { type: 'vanilla', release: false, id: '13w22a' },
  { type: 'vanilla', release: false, id: '13w21b' },
  { type: 'vanilla', release: false, id: '13w21a' },
  { type: 'vanilla', release: false, id: '13w19a' },
  { type: 'vanilla', release: false, id: '13w18c' },
  { type: 'vanilla', release: false, id: '13w18b' },
  { type: 'vanilla', release: false, id: '13w18a' },
  { type: 'vanilla', release: false, id: '13w17a' },
  { type: 'vanilla', release: true, id: '1.5.2' },
  { type: 'vanilla', release: false, id: '13w16b' },
  { type: 'vanilla', release: false, id: '13w16a' },
  { type: 'vanilla', release: true, id: '1.5.1' },
  { type: 'vanilla', release: false, id: '1.5' },
  { type: 'vanilla', release: true, id: '1.4.7' },
  { type: 'vanilla', release: true, id: '1.4.6' },
  { type: 'vanilla', release: true, id: '1.4.5' },
  { type: 'vanilla', release: true, id: '1.4.4' },
  { type: 'vanilla', release: false, id: '1.4.3' },
  { type: 'vanilla', release: true, id: '1.4.2' },
  { type: 'vanilla', release: false, id: '1.4.1' },
  { type: 'vanilla', release: false, id: '1.4' },
  { type: 'vanilla', release: true, id: '1.3.2' },
  { type: 'vanilla', release: true, id: '1.3.1' },
  { type: 'vanilla', release: false, id: '1.3' },
  { type: 'vanilla', release: true, id: '1.2.5' },
  { type: 'vanilla', release: true, id: '1.2.4' },
  { type: 'vanilla', release: true, id: '1.2.3' },
  { type: 'vanilla', release: true, id: '1.2.2' },
  { type: 'vanilla', release: true, id: '1.2.1' },
  { type: 'vanilla', release: true, id: '1.1' },
  { type: 'vanilla', release: true, id: '1.0' },
  { type: 'vanilla', release: false, id: 'b1.8.1' },
  { type: 'vanilla', release: false, id: 'b1.8' },
  { type: 'vanilla', release: false, id: 'b1.7.3' },
  { type: 'vanilla', release: false, id: 'b1.7.2' },
  { type: 'vanilla', release: false, id: 'b1.7' },
  { type: 'vanilla', release: false, id: 'b1.6.6' },
  { type: 'vanilla', release: false, id: 'b1.6.5' },
  { type: 'vanilla', release: false, id: 'b1.6.4' },
  { type: 'vanilla', release: false, id: 'b1.6.3' },
  { type: 'vanilla', release: false, id: 'b1.6.2' },
  { type: 'vanilla', release: false, id: 'b1.6.1' },
  { type: 'vanilla', release: false, id: 'b1.6' },
  { type: 'vanilla', release: false, id: 'b1.5_01' },
  { type: 'vanilla', release: false, id: 'b1.5' },
  { type: 'vanilla', release: false, id: 'b1.4_01' },
  { type: 'vanilla', release: false, id: 'b1.4' },
  { type: 'vanilla', release: false, id: 'b1.3_01' },
  { type: 'vanilla', release: false, id: 'b1.3b' },
  { type: 'vanilla', release: false, id: 'b1.2_02' },
  { type: 'vanilla', release: false, id: 'b1.2_01' },
  { type: 'vanilla', release: false, id: 'b1.2' },
  { type: 'vanilla', release: false, id: 'b1.1_02' },
  { type: 'vanilla', release: false, id: 'b1.1_01' },
  { type: 'vanilla', release: false, id: 'b1.0.2' },
  { type: 'vanilla', release: false, id: 'b1.0_01' },
  { type: 'vanilla', release: false, id: 'b1.0' },
  { type: 'vanilla', release: false, id: 'a1.2.6' },
  { type: 'vanilla', release: false, id: 'a1.2.5' },
  { type: 'vanilla', release: false, id: 'a1.2.4_01' },
  { type: 'vanilla', release: false, id: 'a1.2.3_04' },
  { type: 'vanilla', release: false, id: 'a1.2.3_02' },
  { type: 'vanilla', release: false, id: 'a1.2.3_01' },
  { type: 'vanilla', release: false, id: 'a1.2.3' },
  { type: 'vanilla', release: false, id: 'a1.2.2b' },
  { type: 'vanilla', release: false, id: 'a1.2.2a' },
  { type: 'vanilla', release: false, id: 'a1.2.1_01' },
  { type: 'vanilla', release: false, id: 'a1.2.1' },
  { type: 'vanilla', release: false, id: 'a1.2.0_02' },
  { type: 'vanilla', release: false, id: 'a1.2.0_01' },
  { type: 'vanilla', release: false, id: 'a1.2.0' },
  { type: 'vanilla', release: false, id: 'a1.1.2_01' },
  { type: 'vanilla', release: false, id: 'a1.1.2' },
  { type: 'vanilla', release: false, id: 'a1.1.0' },
  { type: 'vanilla', release: false, id: 'a1.0.17_04' },
  { type: 'vanilla', release: false, id: 'a1.0.17_02' },
  { type: 'vanilla', release: false, id: 'a1.0.16' },
  { type: 'vanilla', release: false, id: 'a1.0.15' },
  { type: 'vanilla', release: false, id: 'a1.0.14' },
  { type: 'vanilla', release: false, id: 'a1.0.11' },
  { type: 'vanilla', release: false, id: 'a1.0.5_01' },
  { type: 'vanilla', release: false, id: 'a1.0.4' },
  { type: 'vanilla', release: false, id: 'inf-20100618' },
  { type: 'vanilla', release: false, id: 'c0.30_01c' },
  { type: 'vanilla', release: false, id: 'c0.0.13a' },
  { type: 'vanilla', release: false, id: 'c0.0.13a_03' },
  { type: 'vanilla', release: false, id: 'c0.0.11a' },
  { type: 'vanilla', release: false, id: 'rd-161348' },
  { type: 'vanilla', release: false, id: 'rd-160052' },
  { type: 'vanilla', release: false, id: 'rd-20090515' },
  { type: 'vanilla', release: false, id: 'rd-132328' },
  { type: 'vanilla', release: false, id: 'rd-132211' },
];
