export const startConsoles = [
  '[00:15:29] [ServerMain/INFO]: Building unoptimized datafixer',
  "[00:15:29] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'",
  '[00:15:31] [ServerMain/INFO]: Loaded 7 recipes',
  '[00:15:31] [ServerMain/INFO]: Loaded 1179 advancements',
  '[00:15:32] [Server thread/INFO]: Starting minecraft server version 1.00.0',
  '[00:15:32] [Server thread/INFO]: Loading properties',
  '[00:15:32] [Server thread/INFO]: Default game type: SURVIVAL',
  '[00:15:32] [Server thread/INFO]: Generating keypair',
  '[00:15:32] [Server thread/INFO]: Starting Minecraft server on *:25565',
  '[00:15:32] [Server thread/INFO]: Using default channel type',
  '[00:15:32] [Server thread/INFO]: Preparing level "world"',
  '[00:15:33] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld',
  '[00:15:35] [Worker-Main-1/INFO]: Preparing spawn area: 0%',
  '[00:15:35] [Worker-Main-1/INFO]: Preparing spawn area: 0%',
  '[00:15:35] [Worker-Main-5/INFO]: Preparing spawn area: 0%',
  '[00:15:35] [Worker-Main-3/INFO]: Preparing spawn area: 0%',
  '[00:15:35] [Worker-Main-6/INFO]: Preparing spawn area: 0%',
  '[00:15:35] [Worker-Main-3/INFO]: Preparing spawn area: 75%',
  '[00:15:35] [Server thread/INFO]: Time elapsed: 2616 ms',
  '[00:15:35] [Server thread/INFO]: Done (3.637s)! For help, type "help"',
];

export const stopConsoles = [
  '[02:05:41] [Server thread/INFO]: Stopping the server',
  '[02:05:41] [Server thread/INFO]: Stopping server',
  '[02:05:41] [Server thread/INFO]: Saving players',
  '[02:05:41] [Server thread/INFO]: Saving worlds',
  "[02:05:42] [Server thread/INFO]: Saving chunks for level 'ServerLevel[worlds/Saku/world]'/minecraft:overworld",
  "[02:05:43] [Server thread/INFO]: Saving chunks for level 'ServerLevel[worlds/Saku/world]'/minecraft:the_end",
  "[02:05:43] [Server thread/INFO]: Saving chunks for level 'ServerLevel[worlds/Saku/world]'/minecraft:the_nether",
  '[02:05:43] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved',
  '[02:05:43] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved',
  '[02:05:43] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved',
  '[02:05:43] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved',
];
