name: Vitest

on: [pull_request]
jobs:
  vitest:
    runs-on: ubuntu-latest
    
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
      - name: 'Install Bun'
        uses: oven-sh/setup-bun@v2
        with:
            bun-version-file: package.json
      - name: 'Install Deps'
        run: bun install
      - name: 'Execute Test'
        run: bun run test --run --coverage --passWithNoTests
      - name: Coverage Report
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2.5.0
